### ISSUE TITLE
Text is stretched

### ISSUE THREAD

**Issue by iangudger** [seehuhn/go-pdf#2]
I used `(*document.MultiPage).AddPage()` and `(*document.Page).SetPageSize` to create multiple pages in a `document.MultiPage` with different sizes. If text is added to these pages with `(*graphics.Page).TextStart`, `(*graphics.Page).TextSetFont`, `(*graphics.Page).TextFirstLine`, `(*graphics.Page).TextShow`, and `(*graphics.Page).TextEnd`, the text is stretched on each page based on each page's aspect ratio.

**Comment by seehuhn** [comment]
Thank you for your report.  Can you send some Go code I can use to reproduce the problem?

**Comment by iangudger** [comment]
I realized that I misunderstood the implications of `(*document.Page).Scale`.

**Comment by seehuhn** [comment]
Ah, good that this is sorted.  Eventually there will be better documentation, but this is still work in progress.  The methods of `*document.Page` are meant to translate relatively directly into the graphics operators described in chapter 8 of the PDF spec.
