### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by iangudger** [seehuhn/go-pdf#3]
It would be really useful to be able to embed an SVG in a PDF.

**Comment by seehuhn** [comment]
Thank you for your suggestion.  I believe this functionality would be best implemented as a separate library, which knows about the SVG format and then translates SVG primitives into calls to the corresponding [`graphics.Page` object](https://pkg.go.dev/seehuhn.de/go/pdf/graphics#Page) methods.  Once you have code to parse SVG files this should be easy to implement, but the go-pdf library does not seem to be the best place for this code.
