### ISSUE TITLE
fish panic when invoking content.ForAllText

### ISSUE THREAD

**Issue by haraldrudell** [seehuhn/go-pdf#4]
Great library, I fall back on ghostscript on pdf corruption

I get a string "fish" panic when invoking content.ForAllText
seehuhn.de/go/pdf/content.ForAllText.func2.1
  /Users/foxyboy/go/pkg/mod/seehuhn.de/go/pdf@v0.3.6/content/extract.go:223

if I use my own code I change line 223 to:
```
panic(perrors.ErrorfPF("unknown graphics state key: %q", key))
// import "github.com/haraldrudell/parl/perrors"
```

In a 2006 pdf, “SM” is used
Attached is the erroring pdf

some thoughts:
it is good software engineering practice to only use error values as panic arguments
ErrorfPF contains a stack trace that can be printed using perrors.Long
perrors.Short prints message with a short code reference 
error messages should be actionable

it is better to return error rather than panic for anything that is recoverable, such as corrupt file data

The object model is peculiar: generic pdf.Object values are handed to top-level functions
of sub-packages. What value goes with which function is unclear. It is therefore difficult to understand how the library is to be used.
Objects should be based on world concepts, so Document is the top-level
Document then has methods to return number of pages, pages and so forth. In this way, library usage would be obvious.
What in 0.3.6 is different packages should be different types (struct/methods) of the same package. It is important that api is real-world object and usage, even if an internal disposition comes from the pdf specification

strings like “MediaBox” should be const that can be searched for, used by api consumers and aren’t misspelled. I also ran into MediaBox value being Array or Rectangle. With supporting multiple versions, shims is a good approach because it tags code with why it exists

pagetree should only be a separate package if its intended to be used separate from Open. It is better a type of the same package

Note that in Go, methods for the same object can go in different files, so many methods is not a problem

New-functions enhance encapsulation. A New function should not store pointers to its created object even in the object itself, or launch threads or return anything other than a single pointer to the value created

If a function literal ends up being used, in Go that means another struct needs to be created with the literal function as a method

[aspect.pdf](https://github.com/seehuhn/go-pdf/files/12744296/aspect.pdf)

**Comment by seehuhn** [comment]
Dear Harald,

Thank you for your report, I will look into this.  I think the main thing to notice is that the library is work in progress, and in particular the code in `seehuhn.de/go/pdf/content` is just an early draft.  The `panic()` statements are just a debugging aid for myself, as the code stabilises I'll remove all stray `panic()` calls, add documentation etc.

Thank you for your design advice, too.

All the best,
Jochen

**Comment by seehuhn** [comment]
I just checked what is going on: I wrote this code to parse a specific document, and I implement only the graphics state parameter dictionary keys used in this document.  So the solution will be to (1) implement the missing keys, and (2) decide what to do when invalid keys are encountered.
