### ISSUE TITLE
Drawing an image in the coordinates I need.

### ISSUE THREAD

**Issue by alhaos** [seehuhn/go-pdf#5]
I just can’t figure out how to draw an image in the place I need, could you please give me an example.
The example shown draws it at the bottom left.

**Comment by seehuhn** [comment]
Thank you for your report.  As you can see, this library is not yet finished, the API is still in flux, and there is currently very little documentation.  The methods for producing graphics are closely aligned with the corresponding PDF operators, so it may help to check the (freely available) PDF spec for inspiration until the library grows proper documentation.  To solve the concrete problem of how to place an image, I'll add an example to the repository.

**Comment by alhaos** [comment]
thank you.
