### ISSUE TITLE
How to import an existing pdf file?How to automatically wrap long text?

### ISSUE THREAD

**Issue by ibryang** [seehuhn/go-pdf#7]
How to import an existing pdf file?
How to automatically wrap long text?

**Comment by seehuhn** [comment]
There are some beginnings of a line breaking algorithm at [https://github.com/seehuhn/go-layout](https://github.com/seehuhn/go-layout) .  This is still work in progress, sorry about the current lack of documentation.

I'll add some example code on how to include an existing PDF file soon.
