### ISSUE TITLE
Got "invalid cross-reference table" when reading PDF exported from Microsoft Word

### ISSUE THREAD

**Issue by eriks1** [seehuhn/go-pdf#8]
Something seems problematic reading the file ending:

[Test POA v2.pdf](https://github.com/seehuhn/go-pdf/files/14482787/Test.POA.v2.pdf)

**Comment by seehuhn** [comment]
Thank you for your report, and for attaching the file.  I'll have a look.

**Comment by seehuhn** [comment]
The problem with the file is that it has an empty cross-reference table, which does not define any objects:
```
xref
0 0
trailer
```

I haven't checked whether the spec allows this, but in either case, I'll modify my code to allow empty cross reference tables.

**Comment by eriks1** [comment]
That's great. Thanks!

Den tis 5 mars 2024 08:38Jochen Voss ***@***.***> skrev:
